apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: monitoring
spec:
  interval: 1h
  timeout: 10m
  releaseName: prom-stack
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.12.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring

  values:
    alertmanager:
      enabled: false

    grafana:
      initChownData: { enabled: false }
      admin:
        existingSecret: grafana-secrets
        userKey: admin-user
        passwordKey: admin-password
      resources:
        requests: { cpu: 50m, memory: 512Mi }
        limits: { cpu: 50m, memory: 512Mi }
      persistence:
        enabled: true
        type: sts
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        size: 3Gi
        finalizers:
          - kubernetes.io/pvc-protection

      additionalDataSources:
        - name: Loki
          uid: loki
          type: loki
          url: http://loki-loki-distributed-gateway
          isDefault: false

        - name: Tempo
          uid: tempo
          type: tempo
          url: http://tempo-query-frontend:3200
          isDefault: false

    prometheus:
      prometheusSpec:
        enableRemoteWriteReceiver: true
        resources:
          requests: { cpu: 100m, memory: 512Mi }
          limits: { cpu: 100m, memory: 512Mi }
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

    prometheusOperator:
      resources:
        requests: { cpu: 25m, memory: 64Mi }
        limits: { cpu: 25m, memory: 64Mi }

    kube-state-metrics:
      resources:
        requests: { cpu: 25m, memory: 64Mi }
        limits: { cpu: 25m, memory: 64Mi }

    prometheus-node-exporter:
      resources:
        requests: { cpu: 25m, memory: 64Mi }
        limits: { cpu: 25m, memory: 64Mi }
    